sonar.projectKey=skyconnect-booking-service
sonar.projectName= SkyConnect Booking Service
sonar.projectVersion=1.0
sonar.soures=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.exclusions=\
	**/model/**,\
	**/dto/**,\
	**/exception/*Eception.java,\
	**/BookingServiceApplication.java,\
	**/config/AppConfig.java
sonar.test.exclusions=**/test/**
sonar.java.source=17